from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import google.generativeai as genai
import os
from dotenv import load_dotenv
import json

# Load environment variables from .env file
load_dotenv(override=True)

app = FastAPI()

# Configure set Gemini API
API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    print("WARNING: GEMINI_API_KEY not found in environment variables.")
else:
    genai.configure(api_key=API_KEY)

class IdeaRequest(BaseModel):
    sentence: str

@app.post("/generate")
async def generate_startup_info(request: IdeaRequest):
    if not API_KEY:
        raise HTTPException(status_code=500, detail="Gemini API key not configured on server. Please add it to your .env file.")
        
    prompt = f"""
You are an expert AI Co-Founder. The user has provided the following startup idea:
"{request.sentence}"

Please provide a structured response in pure JSON format containing the following three items:
1. "lean_canvas": A dictionary mapping the 9 core areas of a Lean Canvas to single, readable strings. Do NOT use arrays/lists for these values. Write them as continuous sentences or plain text paragraphs. The keys must be: "problem", "solution", "unique_value_proposition", "unfair_advantage", "customer_segments", "key_metrics", "channels", "cost_structure", "revenue_streams".
2. "competitors": A list of 5 dictionaries, each with "name" and "description". Crucially, focus on competitors operating in or relevant to Pakistan. If none exist locally, list major international players that serve Pakistan.
3. "pitch_deck": A list of 5 dictionaries representing slides, each with "title" and a list of "points".

Output ONLY valid JSON without Markdown:
"""
    try:
        model = genai.GenerativeModel('gemini-flash-lite-latest')
        # enforce JSON response mime type
        generation_config = genai.types.GenerationConfig(
            response_mime_type="application/json",
            temperature=0.2,
        )
        response = model.generate_content(prompt, generation_config=generation_config)
        
        # Parse the JSON response
        try:
            result = json.loads(response.text)
            return result
        except json.JSONDecodeError:
            print("Failed to decode JSON from Gemini response:", response.text)
            raise HTTPException(status_code=500, detail="Invalid JSON generated by AI.")
            
    except Exception as e:
        print(f"Error during Gemini generation: {e}")
        raise HTTPException(status_code=500, detail=str(e))
